### ISSUE TITLE
Great Stuff. Way to automate so you dont have to click a lot?

### ISSUE THREAD

**Issue by samboa86** [gallowaylabs/streamdeck-tomato-timer#1]
I just started using this, its cool! I hope it makes me more productive. 
Is there a way, or can there be a way, so that it automatically goes into the next timer without having to click?
I feel like we can 'cheat' it if we have to click to start the break, or click to start the next work cycle, etc. 
If it automatically went to the next work cycle, or a way to toggle that option, that would be great!

**Comment by samboa86** [comment]
Actually there seems to be a problem where I have to click the button twice.
-Once when the timer ends, to "clear" it. 
-Then again to start the next one.
Seems like a lot of unnecessary clicking!

**Comment by mgway** [comment]
Having to click twice when the timer ends isn't a problem, that's how it was designed. In the very first version there was no sound effect when the timer expired and it was easy for me to miss the flashing button on the stream deck, so I made it so that you had to press the button to acknowledge you saw that the timer expired. As for your first suggestion, I think I'll add the following settings dropdown:
```
When the timer ends:
- Press once to stop alarm, press again to start next phase timer
- Press once to stop alarm and immediately start next phase timer
- Automatically start next phase when alarm finishes ringing
```

The first option is the current behavior, the second cuts down on button presses but still makes people acknowledge that the timer expired and the third option is the most hands-off version.

**Comment by samboa86** [comment]
Awesome awesome. thanks for the fast reply! My button doesn't flash, its just a solid color. I tried with and without the checkmark about the flashing ubtton. I am using the "transparent" button. So not sure if I encountered a bug there

**Comment by mgway** [comment]
I've added the "When the timer ends" option as described above as well as fixing the transparent button not blinking as expected. You can download it from [the releases page](https://github.com/gallowaylabs/streamdeck-tomato-timer/releases/tag/0.4.0) and check it out immediately or wait a few days for the new version to be approved in the Stream Deck Store and it'll update automatically.
