### ISSUE TITLE
Does not install in Streamdeck

### ISSUE THREAD

**Issue by JensenCR** [gallowaylabs/streamdeck-tomato-timer#10]
I've had this installed on my Streamdeck for a month.  It suddenly disappeared.  I attempted multiple times to reinstall.  From Streamdeck store, I can click install and it says complete, but never shows up in the app.  I've attempted multiple times in many different ways...same result.  My Streamdeck version is 6.2.1.18825

**Comment by mgway** [comment]
I've noticed that this sometimes happens to me if I've installed a plugin outside of the stream deck store and then the stream deck store version is updated. I'm not sure if you did that, but I've at least seen a similar thing happen. 

In any case, the following worked for me in the past:
- Find the stream deck app in your taskbar, right click and Exit
- In file explorer, navigate to `%APPDATA%\Elgato\StreamDeck\Plugins` (aka `C:\Users\<username>\AppData\Roaming\Elgato\StreamDeck`)
- Delete the "com.gallowaylabs.tomato.sdPlugin" directory
- Launch the Stream Deck app again
- Search for tomato timer in the stream deck store and install it

**Comment by JensenCR** [comment]
Well, I've tried all the above, plus reinstalling streamdeck.  No luck.  Too bad, Your app is my favorite!!!  Let me know if any developments which would change my luck!

**Comment by mgway** [comment]
Perhaps one more attempt of deleting the folder and then installing the `.streamDeckPlugin` file on the releases page? https://github.com/gallowaylabs/streamdeck-tomato-timer/releases/tag/v0.6.0

I'm not sure this would prove any different since when I submit the plugin to the stream deck store I just email them a link to that download page but it might be worth a shot.

**Comment by JensenCR** [comment]
OK, that worked!  Thanks a bunch.  Back to productivity...
